# Generated by Django 3.1.3 on 2022-11-25 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scode', models.CharField(max_length=10, null=True)),
                ('sdate', models.DateTimeField(blank=True, null=True)),
                ('qty', models.IntegerField(default=0)),
                ('amt', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pcode', models.CharField(max_length=10, null=True, unique=True)),
                ('pname', models.TextField()),
                ('jang', models.TextField()),
                ('ptime', models.IntegerField(default=0)),
                ('unitprice', models.IntegerField(default=0)),
                ('discountrate', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('img_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id', 'pcode')},
            },
        ),
    ]
